Bugfix: Making it possible to set extra properties for AV/Media heartbeats
at-internet/piano-analytics-android pull request #3
Opened 2023-05-25 08:18 UTC by felix-ulmer

We had the problem with the SDK before that all our heartbeat events were missing all of the av insights standard + custom properties like the `av_content_x` - Properties.

This PR is fixing this by:
* Adding a field to the `Media` - class to store the `extraProps` - map + making it accessible.
* Using that field in the runnables for the heartbeats in `AVRunnable` to pass the extraProps instead of `null` as it was before.

2023-05-29 07:43 UTC, DeKaN commented
Hi @felix-ulmer, we're planning to release `develop` branch as the next version. I recommend using this branch as target for the PR

2023-05-31 13:41 UTC, felix-ulmer commented
> @felix-ulmer Due to global changes in the `develop` branch simple merging is not enough for this PR

Yes, I saw that today unfortunately! :( I'm currently redoing the changes based on the new architecture of the `develop` branch + Kotlin.

2023-06-01 10:39 UTC, DeKaN requested changes

2023-06-01 10:39 UTC, DeKaN commented on piano-analytics/src/main/java/io/piano/android/analytics/MediaHelper.kt
> +        this.extraProps = extraProps
Array values can be modified outside, it's better to make a copy here via `extraProps.copyOf()`

2023-06-01 10:39 UTC, DeKaN commented on piano-analytics/src/main/java/io/piano/android/analytics/MediaHelper.kt
> +    fun setExtraProps(extraProps: Array<out Property>) = apply {
May be we should add `fun setExtraProps(vararg extraProps: Property) = setExtraProps(extraProps)` also. What do you think?

2023-06-05 13:24 UTC, DeKaN approved these changes

2023-06-05 13:32 UTC, merged